name: Deploy to staging - e2e test - prod - e2e test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  staging:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      NODE_ENV: staging
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GET_PRIME_URL: '${{ secrets.GET_PRIME_URL_STAGING }}'
      BASE_URL: 'https://prime-staging-0.web.app'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase for client
        run: npm run deploy:staging -w client

      - name: Deploy to Firebase for server
        run: npm run deploy:staging -w server

      - name: wait for Staging env to be ready
        run: npm run wait:staging

      - name: Run e2e tests on Staging
        run: npm run e2e:staging

  prod:
    runs-on: ubuntu-latest
    needs: staging

    strategy:
      matrix:
        node-version: [18.x]

    env:
      NODE_ENV: prod
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      GET_PRIME_URL: '${{ secrets.GET_PRIME_URL_PROD }}'
      BASE_URL: 'https://prime-0.web.app'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase for client
        run: npm run deploy:prod -w client

      - name: Deploy to Firebase for server
        run: npm run deploy:prod -w server

      - name: wait for Production env to be ready
        run: npm run wait:prod

      - name: Run e2e tests on Production
        run: npm run e2e:prod
